
name: Test win
on:
  workflow_dispatch:

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      ___X_CMD_GHACTION_X: x6
      ___X_CMD_PKG___VERSION: ${{ github.event.inputs.x-cmd-pkg-version }}
      ___X_CMD_PKG___BRANCH: ${{ github.event.inputs.x-cmd-pkg-branch }}
      ___X_CMD_PKG___SOURCE: ${{ github.event.inputs.x-cmd-pkg-source }}
      ___X_BASH_PKG_BRANCH: ${{ github.event.inputs.x-bash-pkg-branch }}
      ___X_BASH_ENV_BRANCH: ${{ github.event.inputs.x-bash-env-branch }}
      ___X_CMD_PKG_CANDADITE: ${{github.event.inputs.pkg-name}}
      ___X_CMD_PKG_CANDADITE_VERSION: ${{github.event.inputs.pkg-version}}
      WEBHOOK_URL: ${{ secrets.ROBOT }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            x cowsay hi
