

name: Test win
on:
  workflow_dispatch:

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      ___X_CMD_GHACTION_X: x6
      WEBHOOK_URL: ${{ secrets.ROBOT }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        shell: bash
        run: |
          bash --version
          printf "%s\n" "ssh: loding ssh-agent and create ~/.ssh and add known_hosts"
          eval "$(ssh-agent)"
          mkdir -p ~/.ssh
          curl -s https://raw.githubusercontent.com/x-cmd/knownhost/main/dist/all.txt >> ~/.ssh/known_hosts
          [ -z "$ssh_key" ] && return
          printf "%s\n" "$ssh_key" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/known_hosts ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa

          echo 'Run ==> git config --global credential.provider generic'
          git config --global credential.provider generic
          echo 'Run ==> export GPG_TTY=$(tty)'
          export GPG_TTY=$(tty)
          echo 'Test ==> eval "$(curl "https://raw.githubusercontent.com/x-cmd/get/main/x6")"'
          eval "$(curl "https://raw.githubusercontent.com/x-cmd/get/main/x6")"