
name: Test default url
on:
  # schedule:
  #   - cron: '0 18 * * *'
  workflow_dispatch:
    inputs:
      x-cmd-pkg-version:
        description: 'x-cmd pkg version'
        required: true
        default: 'v0.0.1'
      x-cmd-pkg-branch:
        description: 'x-cmd pkg branch'
        required: true
        default: 'main'
      x-bash-pkg-branch:
        description: 'x-bash pkg branch'
        required: true
        default: 'main'
      x-bash-env-branch:
        description: 'x-bash env branch'
        required: true
        default: 'main'

jobs:
  test-default-url:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      ___X_CMD_GHACTION_X: x2
      ___X_CMD_PKG_VERSION: ${{ github.event.inputs.x-cmd-pkg-version }}
      ___X_CMD_PKG_BRANCH: ${{ github.event.inputs.x-cmd-pkg-branch }}
      ___X_BASH_PKG_BRANCH: ${{ github.event.inputs.x-bash-pkg-branch }}
      ___X_BASH_ENV_BRANCH: ${{ github.event.inputs.x-bash-env-branch }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            xws test_default_url && \
            git pull && \
            xws push test_doc
