
name: Test default url
on:
  # schedule:
  #   - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  test-default-url:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      ___X_CMD_GHACTION_X: x2
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            xws test_default_url && \
            git pull && \
            xws push test_doc
