

name: Test win
on:
  workflow_dispatch:

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ windows-latest, ] #  ubuntu-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      ___X_CMD_GHACTION_X: x6
      WEBHOOK_URL: ${{ secrets.ROBOT }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        shell: bash
        run: |
          printf "%s\n" "ssh: loding ssh-agent and create ~/.ssh and add known_hosts"
          eval "$(ssh-agent)"
          mkdir -p ~/.ssh
          curl -s https://raw.githubusercontent.com/x-cmd/knownhost/main/dist/all.txt >> ~/.ssh/known_hosts
          [ -z "$ssh_key" ] && return
          printf "%s\n" "$ssh_key" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/known_hosts ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa

          ssh -T git@github.com || true
          git --version
          which scoop winget choco || true
          winget install --id Git.Git -e --source winget
          GIT_TRACE=1 GIT_SSH_COMMAND="ssh -v" command git clone -c core.autocrlf=false "git@github.com:x-cmd/x6.git"
